languageCode = "en-US"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Yoganath Prabhakar"
# copyright = "Yoganath P"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Personal website of Yoganath Prabhakar | ECE Engineer | Microcontroller Enthusiast"

[author]
  name = "Yoganath Prabhakar"
  image = "img/yoganath_profile.png"
  headline = "ECE Engineer | Microcontroller Enthusiast"
  bio = "Personal website of Yoganath Prabhakar | ECE Engineer | Microcontroller Enthusiast"
  links = [
      { email = "mailto:yoganath.prabhakar@gmail.com" },
      { linkedin = "https://www.linkedin.com/in/yoganathp" },
      { github = "https://github.com/yoganathp" },
      { coffee = "https://www.buymeacoffee.com/yoganathp"},
  #    { hashnode = "https://blog.yoganath.me" },
  ]
